### PR TITLE
Update btnmatrix.md for alignment options

### PR DESCRIPTION
**Pull request by DeonMarais64**

### CODE REVIEW

**Comment by embeddedt** [comment]
Thanks!

**Comment by embeddedt** [comment]
Whoops, just realized this shouldn't be merged to `master` or it will end up in 7.0's documentation. I've reverted it and opened #114.

@kisvegabor We have a lot of PRs accumulating for 7.1. Should we create a branch so they can be merged and tested?

**Comment by kisvegabor** [comment]
@embeddedt 
IIRC when we discussed the new release policy we concluded that we won't create `dev` branches but will merge directly into `master` for faster delivery. 

It seems the missing point from the policy is when to merge the new features and when to create new minor releases.

I think announcing too many minor releases could be inconvenient and noisy. 

What about this schedule for a month:
- 1st: Make a minor or major release depending on the new features (it should be announced on the blog and the forum too)
- 2-15th: Merge only patches, do not merge new features yet
- 15th: Make a patch release and after that merge pending new features (not necessarily announced to lower noise) 
- 16-30th: Accept only patches, feature stop to test the new features

At worst case, if a feature comes on 16th, it needs to wait 1 month to get merged.

What do you think? These are just my first ideas, so don't take them too seriously. :slightly_smiling_face:

**Comment by embeddedt** [comment]
Can we still have a `dev` branch so that core contributors can easily test features without having to wait for the 15th? We can merge `dev` into `master` on the 15th.

**Comment by kisvegabor** [comment]
Sounds great! We can have a permanent `dev` branch in the `docs` repo too.
I'll add them today and update the release policy descriptions.

**Comment by kisvegabor** [comment]
I've created the `dev` branch in docs and lvgl repo and merged the pending features there.

**Pull request merged**
