### PR TITLE
Changed references from lv_conf_templ.h to lv_conf_template.h

### PR DESCRIPTION
**Pull request by cmumford**
This file was renamed in https://github.com/lvgl/lvgl/commit/abfdfd1b20340ae75e0e6929ea085880eec7c304.
As of v6.0 the lv_conf_template.h has been distributed.

This fixes https://github.com/lvgl/docs/issues/160.

### CODE REVIEW

**Comment by embeddedt** [comment]
Please make these changes on `latest`, as `master` is only used for holding the compiled HTML files.

Otherwise this looks good.

**Comment by cmumford** [comment]
Will do. thx.

**Comment by cmumford** [comment]
I'm going to abandon in favor of PR #163. However, this seems to only update the most current version of the docs. How can I correct them for v6 and later - which would still be incorrectd?

**Comment by embeddedt** [comment]
The older 7.x revisions don't matter, as the newer 7.x documentation applies to them as well (with the exception of missing features, which would be expected).

I am not sure if we have a way of easily updating the v6 documentation. @kisvegabor?

**Comment by kisvegabor** [comment]
v6 can be rebuilt as well, but I don't think it's worth to bother with that as it's getting quite old.

**Comment by kisvegabor** [comment]
AS #163 is merged I close this issue.

**Pull request closed without merging**
