### PR TITLE
Updated "Show selected"  section

### PR DESCRIPTION
**Pull request by MiSimon**
Update for the docs to describe changes from this [PR.](https://github.com/lvgl/lvgl/pull/1799)

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you. It's the same here, can you resend against master?

**Comment by MiSimon** [comment]
Sure, which file hast to be modified in the master branch, is can see some .html files and some .md.txt files?

**Comment by kisvegabor** [comment]
Oh sorry, not master, in the docs it's the latest branch.

Here it is: https://github.com/lvgl/docs/blob/latest/widgets/dropdown.md

**Comment by MiSimon** [comment]
I have created a new PR against latest, i am closing this one.

**Pull request closed without merging**
